version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - revive
    - errcheck
    - gocyclo
    - misspell
    - unparam
    - unconvert
    - gosec
  # gosimple is part of the staticcheck suite but our current golangci-lint build
  # omits it; re-enable once binaries include the gosimple analyzer.

formatters:
  enable:
    - gofmt

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
    exclude-functions:
      - (io.Writer).Write
      - (io.ReadCloser).Close
      - (net/http.ResponseWriter).Write
      - (*os.File).Close
      - (*testing.T).Fatal
      - (*testing.T).Fatalf
      - os.Remove
    ignore: tests:UpdatePipelines,tests:Write,tests:Close

  gocyclo:
    min-complexity: 38  # Increased to allow executeEgressHTTP with DLP logic

  revive:
    rules:
      - name: package-comments
        severity: warning
        disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude test files from specific linters
  exclude-dirs:
    - tests

  exclude-rules:
    # Test files - allow unchecked errors and unused parameters
    - path: "tests/"
      linters:
        - revive
        - unparam
        - errcheck

    # Specific test file patterns
    - path: "_test\\.go$"
      linters:
        - errcheck
        - revive
        - unparam

    # OPA SDK deprecation warning - acknowledged, will migrate in future
    - path: "internal/policy/engine\\.go"
      text: "SA1019.*opa/sdk.*deprecated"
      linters:
        - staticcheck

    # Test harness security warnings are expected
    - path: 'tests[\\/]e2e[\\/]harness\.go'
      linters:
        - gosec
