version: '3.8'

services:
  # The Polis proxy core
  polis-core:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: polis-core
    ports:
      - "8090:8090"    # Data plane (proxy listens here)
      - "19090:19090"  # Admin/health endpoints
    environment:
      - LOG_LEVEL=info
      - POLIS_MODE=dev
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./pipeline.yaml:/app/pipeline.yaml:ro
      - ./policies:/app/policies:ro
    command: >
      --config /app/config.yaml
      --log-level info
      --pretty
    networks:
      - polis-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19090/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Sample agent (LangGraph-based) that will be proxied
  agent-demo:
    build:
      context: ./agent-sample
      dockerfile: Dockerfile
    container_name: agent-demo
    ports:
      - "3001:3001"
    environment:
      # Key: All HTTP/HTTPS traffic goes through the proxy
      - HTTP_PROXY=http://polis-core:8090
      - HTTPS_PROXY=http://polis-core:8090
      - NO_PROXY=localhost,127.0.0.1,polis-core
      # Agent config
      - AGENT_PORT=3001
      - LLM_API_KEY=${OPENAI_API_KEY:-sk-demo-key}  # Use .env or export
      - POLIS_PROXY_URL=http://polis-core:8090
    depends_on:
      polis-core:
        condition: service_healthy
    networks:
      - polis-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Observability: Prometheus (optional, for metrics)
  prometheus:
    image: prom/prometheus:latest
    container_name: polis-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - polis-net
    depends_on:
      - polis-core

  # Web UI for viewing traces and policy decisions
  polis-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: polis-ui
    ports:
      - "3000:3000"
    environment:
      - POLIS_API_URL=http://polis-core:8090
      - PROMETHEUS_URL=http://prometheus:9090
    depends_on:
      - polis-core
    networks:
      - polis-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  polis-net:
    driver: bridge

volumes:
  prom-data:
