name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: I also considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Authentication/Authorization
        - Routing/Proxying
        - Policy Enforcement
        - Telemetry/Observability
        - Configuration Management
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking adoption
        - High - Needed soon
        - Medium - Would be nice to have
        - Low - Future consideration
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        We need this feature because...
        It will help us...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        This could be implemented by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I am willing to implement this feature and submit a PR

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or related issues
      placeholder: |
        Related to #issue
        Similar to feature X in product Y
