apiVersion: v1
kind: Namespace
metadata:
	name: polis-demo

---
# ConfigMap for Polis configuration
apiVersion: v1
kind: ConfigMap
metadata:
	name: polis-config
	namespace: polis-demo
data:
	config.yaml: |
		server:
			admin_address: ":19090"
			data_address: ":8090"
		pipeline:
			file: "/etc/polis/pipeline.yaml"
		telemetry:
			otlp_endpoint: "localhost:4317"
			insecure: true
		logging:
			level: "info"

	pipeline.yaml: |
		id: agent-demo-pipeline
		agentId: "*"
		protocol: "http"
		nodes:
			# 1. Log the request
			- id: request_log
				type: log
				config:
					level: "info"
				on:
					success: prompt_injection_check
					failure: request_log

			# 2. Check for prompt injection
			- id: prompt_injection_check
				type: waf
				config:
					action: block
					rules:
						- name: "Prompt Injection - Ignore Instructions"
							pattern: "(?i)(ignore\\s+(all\\s+)?previous\\s+instructions|disregard\\s+your|you\\s+are\\s+now|role\\s+play\\s+as)"
							severity: "high"
							action: "block"
						- name: "Prompt Injection - System Override"
							pattern: "(?i)(system\\s+prompt|developer\\s+mode|reveal\\s+instructions)"
							severity: "high"
							action: "block"
				on:
					success: dlp_check
					failure: deny_injection

			# 3. DLP - Redact PII if enabled
			- id: dlp_check
				type: dlp
				config:
					action: redact
					patterns:
						- name: "Email"
							pattern: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
							redact_with: "[EMAIL_REDACTED]"
						- name: "SSN"
							pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
							redact_with: "[SSN_REDACTED]"
						- name: "Phone"
							pattern: "\\b\\d{3}[-.]?\\d{3}[-.]?\\d{4}\\b"
							redact_with: "[PHONE_REDACTED]"
				on:
					success: upstream_egress
					failure: upstream_egress

			# 4. Forward to upstream (LLM)
			- id: upstream_egress
				type: egress
				config:
					upstream_url: "https://api.openai.com/v1"
				on:
					success: "response_log"
					failure: deny_generic

			# 5. Log response
			- id: response_log
				type: log
				config:
					level: "info"
				on:
					success: ""
					failure: ""

			# Deny nodes
			- id: deny_injection
				type: terminal.deny
				config:
					code: 403
					message: "Prompt injection detected. Request blocked by Polis."

			- id: deny_generic
				type: terminal.deny
				config:
					code: 500
					message: "Internal error processing request."

---
# Service Account for the agent
apiVersion: v1
kind: ServiceAccount
metadata:
	name: agent-sa
	namespace: polis-demo

---
# Pod with Polis sidecar
apiVersion: v1
kind: Pod
metadata:
	name: agent-with-sidecar
	namespace: polis-demo
	labels:
		app: agent-demo
spec:
	serviceAccountName: agent-sa

	initContainers:
		# Initialize iptables to redirect traffic to the sidecar proxy
		- name: iptables-init
			image: busybox:1.35
			command: ['sh', '-c']
			args:
				- |
					# Redirect all outbound TCP traffic to the proxy sidecar
					iptables -t nat -A OUTPUT -p tcp ! -d 127.0.0.1 -o eth0 -j REDIRECT --to-port 8090
					echo "iptables rules configured"
			securityContext:
				capabilities:
					add:
						- NET_ADMIN

	containers:
		# Polis proxy sidecar
		- name: polis-proxy
			image: ghcr.io/polisai/polis-core:latest
			imagePullPolicy: IfNotPresent
			ports:
				- containerPort: 8090
					name: proxy
				- containerPort: 19090
					name: admin
			env:
				- name: LOG_LEVEL
					value: "info"
				- name: POLIS_MODE
					value: "transparent"
			volumeMounts:
				- name: polis-config
					mountPath: /etc/polis
			securityContext:
				capabilities:
					add:
						- NET_ADMIN
			livenessProbe:
				httpGet:
					path: /health
					port: 19090
				initialDelaySeconds: 5
				periodSeconds: 10
			readinessProbe:
				httpGet:
					path: /health
					port: 19090
				initialDelaySeconds: 3
				periodSeconds: 5
			resources:
				requests:
					memory: "128Mi"
					cpu: "100m"
				limits:
					memory: "512Mi"
					cpu: "500m"

		# The actual agent application
		- name: agent-app
			image: ghcr.io/polisai/agent-demo:latest
			imagePullPolicy: IfNotPresent
			ports:
				- containerPort: 3001
					name: http
			env:
				- name: PORT
					value: "3001"
				- name: OPENAI_API_KEY
					valueFrom:
						secretKeyRef:
							name: openai-credentials
							key: api-key
							optional: true
				- name: POLIS_TRANSPARENT_MODE
					value: "true"
			livenessProbe:
				httpGet:
					path: /health
					port: 3001
				initialDelaySeconds: 10
				periodSeconds: 10
			readinessProbe:
				httpGet:
					path: /health
					port: 3001
				initialDelaySeconds: 5
				periodSeconds: 5
			resources:
				requests:
					memory: "256Mi"
					cpu: "200m"
				limits:
					memory: "512Mi"
					cpu: "500m"

			securityContext:
				capabilities:
					add:
						- NET_ADMIN  # For receiving iptables-redirected traffic

	volumes:
		- name: polis-config
			configMap:
				name: polis-config

	securityContext:
		runAsNonRoot: false
		fsGroup: 0

---
# Service to expose the agent
apiVersion: v1
kind: Service
metadata:
	name: polis-agent
	namespace: polis-demo
spec:
	type: ClusterIP
	selector:
		app: agent-demo
	ports:
		- port: 3001
			targetPort: 3001
			name: http

---
# Service to expose Polis admin/metrics
apiVersion: v1
kind: Service
metadata:
	name: polis-admin
	namespace: polis-demo
spec:
	type: ClusterIP
	selector:
		app: agent-demo
	ports:
		- port: 19090
			targetPort: 19090
			name: admin

