id: compliance-pipeline
agentId: "*"
protocol: http
nodes:
  - id: start
    type: auth
    on:
      success: compliance_check
      failure: deny

  - id: compliance_check
    type: policy
    config:
      entrypoint: "policy/compliance/decision"
      posture: "fail-closed"
    on:
      success: egress
      failure: deny

  - id: egress
    type: egress
    config:
      upstream_url: https://api.openai.com
    on:
      success: ""

  - id: deny
    type: terminal.deny
